imagePullSecrets:
  - name: harbor-registry-secret

global:
  image:
    registry: harbor.lan/registry.k8s-cache

controller:
  service:
    annotations:
      metallb.universe.tf/address-pool: metallb-pool-internal
  ingressClassResource:
    name: nginx-internal
    controllerName: "k8s.io/ingress-nginx-internal"
    enabled: true
  ingressClass: nginx-internal
