imagePullSecrets:
  - name: harbor-registry-secret

defaultSettings:
  createDefaultDiskLabeledNodes: true

preUpgradeChecker:
  jobEnabled: false

image:
  longhorn:
    engine:
      # -- Registry for the Longhorn Engine image.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Longhorn Engine image.
      repository: longhornio/longhorn-engine
      # -- Tag for the Longhorn Engine image.
      tag: v1.10.1
    manager:
      # -- Registry for the Longhorn Manager image.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Longhorn Manager image.
      repository: longhornio/longhorn-manager
      # -- Tag for the Longhorn Manager image.
      tag: v1.10.1
    ui:
      # -- Registry for the Longhorn UI image.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Longhorn UI image.
      repository: longhornio/longhorn-ui
      # -- Tag for the Longhorn UI image.
      tag: v1.10.1
    instanceManager:
      # -- Registry for the Longhorn Instance Manager image.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Longhorn Instance Manager image.
      repository: longhornio/longhorn-instance-manager
      # -- Tag for the Longhorn Instance Manager image.
      tag: v1.10.1
    shareManager:
      # -- Registry for the Longhorn Share Manager image.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Longhorn Share Manager image.
      repository: longhornio/longhorn-share-manager
      # -- Tag for the Longhorn Share Manager image.
      tag: v1.10.1
    backingImageManager:
      # -- Registry for the Backing Image Manager image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Backing Image Manager image. When unspecified, Longhorn uses the default value.
      repository: longhornio/backing-image-manager
      # -- Tag for the Backing Image Manager image. When unspecified, Longhorn uses the default value.
      tag: v1.10.1
    supportBundleKit:
      # -- Registry for the Longhorn Support Bundle Manager image.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the Longhorn Support Bundle Manager image.
      repository: longhornio/support-bundle-kit
      # -- Tag for the Longhorn Support Bundle Manager image.
      tag: v0.0.71
  csi:
    attacher:
      # -- Registry for the CSI attacher image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the CSI attacher image. When unspecified, Longhorn uses the default value.
      repository: longhornio/csi-attacher
      # -- Tag for the CSI attacher image. When unspecified, Longhorn uses the default value.
      tag: v4.10.0-20251030
    provisioner:
      # -- Registry for the CSI Provisioner image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the CSI Provisioner image. When unspecified, Longhorn uses the default value.
      repository: longhornio/csi-provisioner
      # -- Tag for the CSI Provisioner image. When unspecified, Longhorn uses the default value.
      tag: v5.3.0-20251030
    nodeDriverRegistrar:
      # -- Registry for the CSI Node Driver Registrar image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the CSI Node Driver Registrar image. When unspecified, Longhorn uses the default value.
      repository: longhornio/csi-node-driver-registrar
      # -- Tag for the CSI Node Driver Registrar image. When unspecified, Longhorn uses the default value.
      tag: v2.15.0-20251030
    resizer:
      # -- Registry for the CSI Resizer image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the CSI Resizer image. When unspecified, Longhorn uses the default value.
      repository: longhornio/csi-resizer
      # -- Tag for the CSI Resizer image. When unspecified, Longhorn uses the default value.
      tag: v1.14.0-20251030
    snapshotter:
      # -- Registry for the CSI Snapshotter image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the CSI Snapshotter image. When unspecified, Longhorn uses the default value.
      repository: longhornio/csi-snapshotter
      # -- Tag for the CSI Snapshotter image. When unspecified, Longhorn uses the default value.
      tag: v8.4.0-20251030
    livenessProbe:
      # -- Registry for the CSI liveness probe image. When unspecified, Longhorn uses the default value.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the CSI liveness probe image. When unspecified, Longhorn uses the default value.
      repository: longhornio/livenessprobe
      # -- Tag for the CSI liveness probe image. When unspecified, Longhorn uses the default value.
      tag: v2.17.0-20251030
  openshift:
    oauthProxy:
      # -- Registry for the OAuth Proxy image. Specify the upstream image (for example, "quay.io/openshift/origin-oauth-proxy"). This setting applies only to OpenShift users.
      registry: "harbor.lan/hub.docker-cache"
      # -- Repository for the OAuth Proxy image. Specify the upstream image (for example, "quay.io/openshift/origin-oauth-proxy"). This setting applies only to OpenShift users.
      repository: ""
      # -- Tag for the OAuth Proxy image. Specify OCP/OKD version 4.1 or later (including version 4.18, which is available at quay.io/openshift/origin-oauth-proxy:4.18). This setting applies only to OpenShift users.
      tag: ""
  # -- Image pull policy that applies to all user-deployed Longhorn components, such as Longhorn Manager, Longhorn driver, and Longhorn UI.
  pullPolicy: IfNotPresent